CREATE TABLE IF NOT EXISTS pqrs_form_﻿cataracts (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `user` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `groupname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL, 
  `purpose` longtext COLLATE utf8_unicode_ci NOT NULL,
  `﻿Cataracts0130` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `﻿Cataracts0191` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `﻿Cataracts0192` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `﻿Cataracts0226` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `﻿Cataracts0303` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `﻿Cataracts0304` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `﻿Cataracts0388` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `﻿Cataracts0389` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `recommendation` longtext COLLATE utf8_unicode_ci NOT NULL,
  `finalize` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
)
