CREATE TABLE IF NOT EXISTS form_cpn (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
data1 TIME NOT NULL,
data2 TIME NOT NULL,
data3 longtext NOT NULL,
data4 longtext NOT NULL,
data5 longtext NOT NULL,
data6 longtext NOT NULL,
data7 longtext NOT NULL,
data8 varchar(3) default NULL,
data9 varchar(3) default NULL,
data10 varchar(3) default NULL,
data11 varchar(3) default NULL,
data12 varchar(3) default NULL,
data13 varchar(3) default NULL,
data14 varchar(3) default NULL,
data15 varchar(3) default NULL,
data16 varchar(3) default NULL,
data17 longtext NOT NULL,
data18 varchar(255) default NULL,
data19 varchar(3) default NULL,
data20 varchar(3) default NULL,
data21 varchar(3) default NULL,
data22 varchar(3) default NULL,
data23 varchar(3) default NULL,
data24 varchar(3) default NULL,
data25 varchar(3) default NULL,
data26 varchar(3) default NULL,
data27 varchar(3) default NULL,
data28 varchar(3) default NULL,
data29 varchar(3) default NULL,
data30 varchar(3) default NULL,
data31 varchar(3) default NULL,
data32 varchar(3) default NULL,
data33 longtext NOT NULL,
data34 longtext NOT NULL,
data35 DATE NOT NULL,
data36 TIME NOT NULL,
data37 TIME NOT NULL,
finalize varchar(3) default NULL,
PRIMARY KEY (id)
) 