CREATE TABLE IF NOT EXISTS form_PMM (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `groupname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `presenting_problem` longtext COLLATE utf8_unicode_ci NOT NULL,
  `currentmeds` longtext COLLATE utf8_unicode_ci NOT NULL,
  `allergies` longtext COLLATE utf8_unicode_ci NOT NULL,
  `appearance` longtext COLLATE utf8_unicode_ci NOT NULL,
  `general` longtext COLLATE utf8_unicode_ci NOT NULL,
  `affect_mood` longtext COLLATE utf8_unicode_ci NOT NULL,
  `speech1` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `speech2` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `speech3` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `speech4` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `speech5` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `speech6` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `speech_notes` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `thought1` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `thought2` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `thought3` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `thought4` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `thought_notes` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `psychoa` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `psychob` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `psychoc` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `psycho_notes` longtext COLLATE utf8_unicode_ci NOT NULL,
  `labs` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `other` longtext COLLATE utf8_unicode_ci NOT NULL,
  `diagchange` longtext COLLATE utf8_unicode_ci NOT NULL,
  `cgas` longtext COLLATE utf8_unicode_ci NOT NULL,
  `medchanges` longtext COLLATE utf8_unicode_ci NOT NULL,
  `changereason` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `changeother` longtext COLLATE utf8_unicode_ci NOT NULL,
  `laborder` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `labother` longtext COLLATE utf8_unicode_ci NOT NULL,
  `appt` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `apptother` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `finalize` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) TYPE=MyISAM;

