CREATE TABLE IF NOT EXISTS pqrs_form_preventive_care (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `user` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `groupname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL, 
  `purpose` longtext COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0039` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0048` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0110` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0111` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0112` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0113` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0128` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0134` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0226` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Preventive_Care0431` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `recommendation` longtext COLLATE utf8_unicode_ci NOT NULL,
  `finalize` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
)
