CREATE TABLE IF NOT EXISTS form_cfars (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
purpose varchar(3) default NULL,
atype varchar(3) default NULL,
species varchar(3) default NULL,
sa_hx varchar(3) default NULL,
education varchar(3) default NULL,
license_num mediumtext NOT NULL,
county varchar(3) default NULL,
depression varchar(3) default NULL,
anxiety varchar(3) default NULL,
hyperactivity varchar(3) default NULL,
thought_process varchar(3) default NULL,
cognitive varchar(3) default NULL,
medical varchar(3) default NULL,
stress varchar(3) default NULL,
substance varchar(3) default NULL,
interpersonal varchar(3) default NULL, 
home varchar(3) default NULL,
adl varchar(3) default NULL,
legal varchar(3) default NULL,
works varchar(3) default NULL,
self varchar(3) default NULL,
dothers varchar(3) default NULL,
security varchar(3) default NULL,
family varchar(3) default NULL,
care varchar(3) default NULL,
counselor_name varchar(255) default NULL,
counselor_id varchar(4) default NULL,
finalize varchar(3) default NULL,
PRIMARY KEY (id)
) 